<?php

function ejabberd_auth_menu() {
	$items['admin/settings/ejabberd_auth'] = array(
		'description' => 'Ejabberd auth with drupal users',
		'title' => 'Ejabberd authentification',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('ejabberd_auth_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		);
	return $items;
}

function ejabberd_auth_admin_settings() {
	$form['ejabberd_auth_path'] = array(
		'#type' => 'textfield',
		'#title' => 'Script path',
		'#default_value' => variable_get('ejabberd_auth_path', '/tmp/'),
		'#description' => t("Where the auth script is generated"),
	);

	$form['ejabberd_auth_salt'] = array(
		'#type' => 'textfield',
		'#title' => 'Salt',
		'#default_value' => variable_get('ejabberd_auth_salt', 'Casimir'),
		'#description' => t("The secret word, don't keep the default one"),
	);

	$form['ejabberd_auth_timeout'] = array(
		'#type' => 'textfield',
		'#title' => 'Timeout',
		'#default_value' => variable_get('ejabberd_auth_timeout', '180'),
		'#description' => t("The secret word, don't keep the default one"),
	);
	return system_settings_form($form);
}

function ejabberd_auth_admin_settings_validate($form, &$form_state) {
	if(! is_numeric($form_state['values']['ejabberd_auth_timeout']))
		form_set_error('ejabberd_auth_timeout', t("Please, I'd like a number"));
}